first version
scilus/extractor_flow pull request #1
Opened 2020-08-13 13:44 UTC by arnaudbore

2020-08-21 17:20 UTC, frheault reviewed
I am currently testing it.

This is the first pass. Main comments
1) A bit more verbose, this ain't enough even for testing
2) A weird mix of camel case and underscore everywhere, I would vote for underscore everwhere possible and clearly cutting word like `noCX_inCereb` into `no_CX_in_cereb` or `assoAllIntraInter` into `asso_all_intra_inter`
3) I think the fact that the input tractogram must be pre-registered to template space is limiting a bit. Considering it is part of nextflow to have an optional process and input I would like the possibility to provide either:
- `*.mat` `*InverseWarp.nii.gz` and `*Warp.nii.gz` to apply the transformation for us (and a `--precomputed_registration` flag)
- `fa.nii.gz` (or `t1.nii.gz`) to lets the nextflow do the registration (a flag for SyN vs SyNQuick could be useful, what does Laurent use?) and a `--do_registration` flag
- Providing nothing and give no flag would mean it is already in template space

(I don't know what is the end goal, but if there is a way we can get bundles out of this version, it would be nice to revert the output trk to native space using the same logic as the registration described above (and a `--warp_back_to_native` flag)

(I would convert all tag to comments, its messing up display. The process name should be clear enough by itself

2020-08-21 17:20 UTC, frheault commented on USAGE
> +                                        By default, will be in "./results"
could the results folder be `results_extractor/` by default ?

This help avoid confusion for user running (even if it is not recommended) multiple flow from the same folder

2020-08-21 17:20 UTC, frheault commented on USAGE
> +
Even if it is in the custom singularity, I would add the   --roisFolder and --filteringListsFolder option.
This will allow the use of tractoflow singularity with the pipeline, if the user extract the tar.bz2 found in the source.
That's what I would do instead of having an extra 3GB of singularity to carry around.

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  roisFolder="/JHU_template_GIN_dil/"
rois_folder

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  filteringListsFolder="/filtering_lists/"
filtering_lists_folder

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  //**Loop**//
Maybe a bit more verbose, variable could be `loop_angle_threshold`

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  assoLists="F_O_dorsal,F_O_dorsal,F_O_ventral,F_O_ventral,F_P_dorsal,F_P_dorsal,F_P_ventral,F_P_ventral,F_T_dorsal,F_T_dorsal,F_T_ventral,F_T_ventral"
asso_lists

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +   atlas.cutGCCMFG='JHU_MNI_cut_GCC_MFG.nii.gz'
Not clear, I think underscore at the right place would help.
Just like the name after: cut_GCC_FrOrb

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +   atlas.avoidCCIFGHomo='JHU_MNI_avoid_CC_IFG_homotopic.nii.gz'
Same, please use underscore where possible

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  ext.notUsed="notUsed"
not_used

2020-08-21 17:20 UTC, frheault commented on nextflow.config
> +  ext.cerebellum="all_cereb"
all_cerebellum

2020-08-21 17:20 UTC, frheault commented on main.nf
> +        .fromFilePairs("$root/**/*{.trk}",
`.fromFilePairs("$root/**/*{.trk}",` -> `.fromFilePairs("$root/**/*.trk",`

2020-08-21 17:20 UTC, frheault commented on main.nf
> +process rm_out_JHU {
Remove_Out_JHU

2020-08-21 17:20 UTC, frheault commented on main.nf
> +process remove_crossing_gyri {
All processes in our nextflow (I think its a convention, @GuillaumeTh) have a upper case at each word of the name (i.e Remove_Crossing_Gyri)

2020-08-21 17:20 UTC, frheault commented on main.nf
> +  set sid, "${sid}_wb_clean01_nocereb.trk" into notEndInCerebellum
set sid, "${sid}_wb_clean01_no_cereb.trk" into not_end_in_cerebellum_for_SOMETHING

No camel case, also most of our process have a SOMETHING_FOR_SOMETHING convention to make the the main more readable (following the flow), is this possible ?

2020-08-21 17:20 UTC, frheault commented on main.nf
> +      scil_filter_streamlines_by_length.py ${tractogram} --minL 20 \
minL and maxL should be parameters that can be modified in the config (just like the angle threshold)
(Adapt name accordingly)

2020-08-21 19:12 UTC, frheault commented on README.md
> +`sudo singularity build singularity_extractorflow.sif singularity_extractorflow.def`
Why `.sif`? Tractoflow still use `.img`

2020-08-23 14:54 UTC, GuillaumeTh requested changes
Amazing work ! :1st_place_medal: I have some comments (as always :stuck_out_tongue: ).

I will not continue for now because I will duplicate my comments. A lot of channels are not used. Please remove them is they are not used. You can see that using -with-dag dag.html option in nextflow. If you have an arrow not linked with a node that mean that this channel is not used and can be deleted.

2020-08-23 14:54 UTC, GuillaumeTh commented on README.md
> +`sudo singularity build singularity_extractorflow.sif singularity_extractorflow.def`
In fact it is the same thing -> Singularity Image File. But yes we use .img in TractoFlow but it will be replaced by .sif one day.

2020-08-23 14:54 UTC, GuillaumeTh commented on Dockerfile
> +FROM scilus/singularity-base-tractoflow:latest
I prefer to have an other repo for Docker and singularity when it is a pipeline.

2020-08-23 14:54 UTC, GuillaumeTh commented on README.md
> +===================
Please add "=" until the end of the "pipeline" word. e.g:
```
ExtractorFlow pipeline
======================
```

2020-08-23 14:54 UTC, GuillaumeTh commented on USAGE
> +                                        By default, will be in "./results"
Agree with Francois. Better to have `results_extractor`

2020-08-23 14:54 UTC, GuillaumeTh commented on USAGE
> +
Agree

2020-08-23 14:54 UTC, GuillaumeTh commented on USAGE
> +===================
Please add "=" until the end of the "pipeline" word. e.g:
```
ExtractorFlow pipeline
======================
```

2020-08-23 14:54 UTC, GuillaumeTh commented on nextflow.config
> +   mode.either_end="either_end"
To test but if it works could be better to have this structure:

```
mode{
either_end="either_end"
both_ends="both_ends"
any="any"
}
```

Same comment for the same type of parameters

2020-08-23 14:54 UTC, GuillaumeTh commented on nextflow.config
> +  ext.cerebellum="all_cereb"
all_ventricules
all_cc
all_dwm

2020-08-23 14:54 UTC, GuillaumeTh commented on nextflow.config
> +    params.Readme_Publish_Dir = "${params.output_dir}/Readme"
You can remove. You don't have a readme

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +(inputTractogram) = in_data
Check but I am pretty sure in_data is already in the good format ;)

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +#!/usr/bin/env nextflow
General comment. Please in the output name files use double underscore. It is usefull when you want to filter. `${sid}__...`

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +process remove_crossing_gyri {
You're right @frheault. Please use this "convention"

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +    set sid, "${sid}_wb_out_JHU.trk" optional true into wb_out_JHU
You don't use this channel. Please delete.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +   set sid, "${sid}_wb_crossing_gyri.trk" optional true into wb_crossing_gyri
You don't use this channel. Please delete.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +    set sid, "${sid}_wb_max20.trk" optional true into wb_max20
You don't use this channel. Please delete.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +  set sid, "${sid}_wb_loops.trk" optional true into wb_loops
You don't use this channel. Please delete.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +      if ${params.keep}
Please add documentation in the USAGE for keep option.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +
Remove empty line

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +
Remove empty line

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +#!/usr/bin/env nextflow
Please use the same indentation between input, output, .... Sometime you add a tab and sometime not.

2020-08-23 14:54 UTC, GuillaumeTh commented on main.nf
> +
Remove empty line

2020-08-25 20:04 UTC, arnaudbore commented on main.nf
> +  set sid, "${sid}_wb_clean01_nocereb.trk" into notEndInCerebellum
This is still missing in commit b547d10

2021-01-21 20:06 UTC, GuillaumeTh commented
Some general comments before a deep review:

Max number of caracters per lines: 100

Remove these types of comments: 
```
/*
Pruning min ${params.min_streaminline_lenght}mm
*/
```

Can you check the processed that I have an error with ? I sent you the names by teams earlier

You have a lot of processes. Maybe the publish dir for the output files can be different than the publish dir for filtering. For example for all the rename processes the publish_dir could be results and for the filtering processes the directory name could be filtering.

Please clean the repo. We don't want the Nextflow and container at the same level or repository

2021-10-08 17:05 UTC, merged